### ISSUE TITLE
TIE Set Timing Out

### ISSUE THREAD

**Issue by scottbrumley** [opendxl/opendxl-tie-client-python#1]
Hi I'm trying to use the set tie_client.set_file_reputation function, but it times out.  Am I missing something simple like setting write permissions on the topic?

I can get information from the get topic just fine.  

**Error Message:** WaitTimeoutException: Timeout waiting for response to message: {fe1e14a4-02bf-410a-a759-37a72237da0c}

**Comment by chrissmith-mcafee** [comment]
This is most likely due to an authorization issue. 

See the following in the FAQ and let us know if it works for you.

https://github.com/opendxl/opendxl-tie-client-python/wiki/FAQ#waittimeoutexception

Thanks.

**Comment by scottbrumley** [comment]
Sorry got caught up.

It indeed was a security setting in ePO.  I will have to play with security settings later to see what the lowest level of access would need to be.  I just changed TIE Server Set Reputation to All Systems.

[cid:image001.png@01D2A965.4C0913A0]

**Comment by chrissmith-mcafee** [comment]
Ok, let us know if you have any more issues.
