### ISSUE TITLE
tie_client.set_external_file_reputation() method is not working

### ISSUE THREAD

**Issue by marineriva** [opendxl/opendxl-tie-client-python#16]
First, I'm working with TIE server version 3.0.0 and DXL version 6.0.0.
I use tiedxlclient 0.3.0 and when I run the tie_client.set_external_file_reputation() method (with the file in /samples/basic), everything is working and  "Event Send" is printed without any error.
![Capture1](https://user-images.githubusercontent.com/56430230/74044636-a42fb480-49cb-11ea-9560-8b9419d8771d.PNG)

But when I consult TIE interface, the external reputation is still "not available".

![Capture2](https://user-images.githubusercontent.com/56430230/74044743-db9e6100-49cb-11ea-9d23-721a461e09c4.PNG)

I tried with known, unknown reputations... Nothing never appens.
However, the set_file_reputation() works perfectly.
I added my certificate in DXL topic authorizations and in TIE policy, I checked the possibility of using external reputations as it's mentionned in documentation.
Maybe I forget something ?

Thank you for help :+1:

**Comment by secufred** [comment]
Could you add the payload used ? 
please note that in the documentation the field 'filename' is said to be optional but this is a mandatory field ( if you don't put it the payload will be sent by nothing will be changed on the tie server )

**Comment by marineriva** [comment]
Yes, there it is : 
        "hashes": {
            "md5": "31dbe8cc443d2ca7fd236ac00a52fb17",
            "sha1": "2d6ca45061b7972312e00e5933fdff95bb90b61b",
            "sha256": "aa3c461d4c21a392e372d0d6ca4ceb1e4d88098d587659454eaf4d93c661880f"
        },

This payload is unknown by my TIE server (GTI and Enterprise). I tried also with known payloads, for same result.

I tried with and without a name, nothing has changed.

**Comment by hbazan** [comment]
Did you enabled External Reputation Provider on the TIE Policy?
Can you check if there are errors on dxlbroker.log? maybe the authorization is failing

**Comment by secufred** [comment]
So indeed : 
1) policy on tie server should have the external reputation enabled
2) the certificate used should be set on the correct topic as send (TIE Server External Reputation Provider Event)
3) correct payload  ex : 
tie_client = TieClient(client)
hashes = {
            HashType.MD5: hash_md5,
            HashType.SHA1: fileSHA1,
            HashType.SHA256: fileSHA256
        } 
# please note that the 3 are not mandatory, you could use less that the 3 hash types
# all yours checks could then be done ( does it have a reputation , ..... ) 
# then push your reputation  : 
tie_client.set_external_file_reputation(
                        TrustLevel.<Level>, #ex :TrustLevel.MOST_LIKELY_TRUSTED, 
                        hashes, # format here above
                        filename="<filename>", # ex : filename="putty.exe", # please note that this is mandatory for the external reputation and optionnal for the enterprise reputation
                        comment=comment) # ex : comment="putty.exe is a most likely trusted file"
please also note that if you have justed added the certificate to the correct authorization topic, this is not directly active 

you could also try to use the sample script provided with this package, it's working

**Comment by marineriva** [comment]
Hi all,
In fact, the TIE server update was poorly done (we recently updated from 2.3 to 3.0 for external reputations). We reinstalled TIE and it's now working.
Thanks a lot !

**Comment by hbazan** [comment]
@marineriva shouldn't we close this issue?
